#!/bin/bash

gpio=( 4 17 18 22 23 24 25 27 )

for i in "${gpio[@]}"
do
	if [ ! -d "/sys/class/gpio/gpio$i" ]; then
		echo $i > /sys/class/gpio/export
	fi
	
done

sleep 1

for i in "${gpio[@]}"
do
	echo out > /sys/class/gpio/gpio${i}/direction
	
done

sleep 1

for i in "${gpio[@]}"
do
	echo 0 > /sys/class/gpio/gpio${i}/value 
	
done
