#!/bin/bash
##
## A script to update TLS fingerprint before running Pianobar.
## Used TLS grabber script by Bob Saska (r35krag0th) <git@r35.net> 
## to pull the tls fingerprint from Pandora.
 
openssl s_client -connect tuner.pandora.com:443 < /dev/null 2> /dev/null | \
openssl x509 -noout -fingerprint | tr -d ':' | cut -d'=' -f2 >> /dev/shm/tls
TLS=$(cat /dev/shm/tls)
sed -i "s/\(tls_fingerprint *= *\).*/\1$TLS/" ~/.config/pianobar/config
rm /dev/shm/tls
pianobar
